FROM jdk11:0408
MAINTAINER massadobe
COPY app.jar /app.jar
ENTRYPOINT ["java","-jar","-DAPPLICATION_PROFILES=dev", \
"-DXXL_EXECUTOR_PORT={{XXL_PORT}}", \
"-DHTTP_PORT=8080", \
"-DGRPC_PORT=9090", \
"/app.jar"]