version: '3.3'

services:

  envoy:
    container_name: test-envoy
    restart: always
    image: envoyproxy/envoy-alpine:v1.21.6
    ports:
      - "{{ENVOY_PORT}}:10408"
      - "{{ADMIN_PORT}}:10417"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./pb/:/etc/envoy/pb/
    depends_on:
      - server
    expose:
      - "10408"
      - "10417"
    networks:
      test_mash:
        aliases:
          - test_envoy_network

  server:
    container_name: test-server
    restart: always
    image: test-server:{{SERVER_TAG}}
    build:
      context: .
    ports:
      - "{{XXL_PORT}}:17001"
      - "{{SERVER_PORT}}:9090"
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - ./log:/var/logs
    expose:
      - "{{XXL_PORT}}"
      - "9090"
    extra_hosts:
      - "dev-mysql:172.17.110.106"
      - "dev-redis:172.17.110.106"
    networks:
      test_mash:
        aliases:
          - test_server_network

networks:
  test_mash:
    driver: bridge
  host:
    external: true