version: '3'

services:
  xxl:
    container_name: xxl-job-admin
    restart: always
    build:
      context: .
    image: xxl-job-admin:{{SERVER_TAG}}
    ports:
      - "38080:38080"
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - ./log:/usr/local/logs/x-team/xxl-job-admin
    extra_hosts:
      - "dev-mysql:172.17.110.106"
    networks:
      xxl_mesh:
        aliases:
          - xxl_admin_network

networks:
  xxl_mesh:
    driver: bridge
  host:
    external: true